import { test, expect } from '@playwright/test';
test('学生メニューは内容が少なくても画面の最下部に表示する',async({page})=>{
  await page.setViewportSize({width:900,height:1000});
  await page.goto('/?role=student');
  const app=await page.locator('.lf-app.lf-student').boundingBox();
  const nav=await page.getByRole('navigation',{name:'学生メニュー'}).boundingBox();
  expect(app).not.toBeNull();
  expect(nav).not.toBeNull();
  expect(app!.height).toBe(800);
  await expect(page.locator('.lf-app.lf-student')).toHaveCSS('background-color','rgb(255, 255, 255)');
  await expect(page.locator('.lf-topbar')).toHaveCSS('background-color','rgb(255, 255, 255)');
  await expect(page.locator('.lf-item-card').first()).toHaveCSS('background-color','rgb(247, 247, 247)');
  await expect(page.locator('.lf-item-card').first()).toHaveCSS('border-top-style','none');
  await expect(page.locator('.lf-search-bar')).toHaveCSS('background-color','rgb(247, 247, 247)');
  await expect(page.locator('.lf-search-bar')).toHaveCSS('border-top-style','none');
  await expect(page.locator('.lf-item-card').first()).toHaveCSS('border-radius','8px');
  await expect(page.locator('.lf-search-bar')).toHaveCSS('border-radius','8px');
  expect(Math.abs((nav!.y+nav!.height)-(app!.y+app!.height))).toBeLessThanOrEqual(1);
  await page.getByRole('button',{name:/長傘/}).click();
  const overlay=await page.locator('.lf-overlay').boundingBox();
  const dialog=await page.getByRole('dialog',{name:'拾得物の詳細'}).boundingBox();
  expect(overlay).not.toBeNull();
  expect(dialog).not.toBeNull();
  expect(Math.abs(overlay!.x-app!.x)).toBeLessThanOrEqual(1);
  expect(Math.abs(overlay!.y-app!.y)).toBeLessThanOrEqual(1);
  expect(Math.abs(overlay!.width-app!.width)).toBeLessThanOrEqual(1);
  expect(Math.abs(overlay!.height-app!.height)).toBeLessThanOrEqual(1);
  expect(dialog!.y).toBeGreaterThanOrEqual(app!.y);
  expect(dialog!.y+dialog!.height).toBeLessThanOrEqual(app!.y+app!.height);
  await expect(page.getByRole('dialog',{name:'拾得物の詳細'})).toHaveCSS('box-shadow','none');
  await expect(page.getByRole('dialog',{name:'拾得物の詳細'})).toHaveCSS('border-top-style','none');
  await expect(page.getByRole('dialog',{name:'拾得物の詳細'})).toHaveCSS('border-radius','8px');
  await page.getByRole('dialog').getByRole('button',{name:'閉じる',exact:true}).click();
  await page.getByRole('textbox',{name:'キーワードで探す'}).fill('一致しない検索条件');
  const filteredApp=await page.locator('.lf-app.lf-student').boundingBox();
  expect(filteredApp!.height).toBe(app!.height);
});
test('申告なしの返却は唯一の拾得物一覧から共通の返却対応へ進む',async({page})=>{
  await page.setViewportSize({width:1440,height:1000});await page.goto('/?role=staff');
  await expect(page.getByRole('navigation',{name:'職員メニュー'}).getByRole('button',{name:'返却対応',exact:true})).toHaveCount(0);
  await expect(page.getByRole('button',{name:'事前申告なしで対応',exact:true})).toHaveCount(0);
  await page.getByRole('navigation',{name:'職員メニュー'}).getByRole('button',{name:'保管中の拾得物',exact:true}).click();
  await page.getByRole('button',{name:/長傘/}).click();
  await page.getByRole('button',{name:'返却する',exact:true}).click();
  await expect(page.getByRole('dialog',{name:'本人確認・返却記録',exact:true})).toBeVisible();
  await expect(page.getByRole('button',{name:'返却済みにする'})).toBeDisabled();
  await page.getByRole('dialog').getByLabel('返却先の学校メール（学籍番号付き）').fill('test123@stu.kobe-u.ac.jp');
  await page.getByRole('checkbox',{name:'現物と申告内容を確認し、本人確認を完了しました'}).check();
  await page.getByRole('button',{name:'返却済みにする'}).click();
  await expect(page.getByText('返却を記録しました。')).toBeVisible();
  const db=await page.evaluate(()=>JSON.parse(localStorage.getItem('lost-found-no-qr-test-harness-v1')!));
  expect(db.claims).toHaveLength(0);
  expect(db.items.find((row:{id:string})=>row.id==='1').value).toMatchObject({status:'返却済み',recipientEmail:'test123@stu.kobe-u.ac.jp',claimId:''});
  await expect(page.getByRole('button',{name:'この品物で返却対応',exact:true})).toHaveCount(0);
  await page.getByRole('navigation',{name:'職員メニュー'}).getByRole('button',{name:'保管中の拾得物',exact:true}).click();
  await page.getByRole('button',{name:/ペンケース/}).click();
  await page.getByRole('button',{name:'返却する',exact:true}).click();
  await expect(page.getByRole('dialog',{name:'本人確認・返却記録',exact:true})).toBeVisible();
  await expect(page.getByRole('dialog')).toContainText('ペンケース');
  await expect(page.getByRole('dialog').getByLabel('返却先の学校メール（学籍番号付き）')).toHaveValue('');
  await expect(page.getByRole('button',{name:'返却済みにする'})).toBeDisabled();
  await page.getByRole('dialog').getByRole('button',{name:'閉じる',exact:true}).click();
  await expect(page.getByRole('dialog',{name:'拾得物の詳細'})).toBeVisible();
});
test('スマホで検索・紛失届、職員が登録・手動返却、本人の履歴へ',async({page,context})=>{
  await page.setViewportSize({width:390,height:844});await page.goto('/?role=student');
  expect((await page.locator('.lf-app.lf-student').boundingBox())!.height).toBe(844);
  await expect(page.getByLabel('お名前')).toHaveCount(0);
  await expect(page.getByLabel('学校メール（学籍番号付き・必須）')).toHaveCount(0);
  await expect(page.getByRole('button',{name:'保存する',exact:true})).toHaveCount(0);
  await page.getByRole('navigation',{name:'学生メニュー'}).getByRole('button',{name:'探す',exact:true}).click();
  await expect(page.getByRole('textbox',{name:'キーワードで探す'})).toBeVisible();
  const firstItem=page.getByRole('button',{name:/長傘/});
  await expect(firstItem.getByText(/^#/)).toHaveCount(0);
  await expect(firstItem.getByText('保管中',{exact:true})).toHaveCount(0);
  await expect(firstItem.getByText('色：黒・白',{exact:true})).toBeVisible();
  await expect(firstItem.getByText('特徴：持ち手が木製、白い縁取り',{exact:true})).toBeVisible();
  await expect(firstItem.getByText('保管場所：農学部事務室',{exact:true})).toBeVisible();
  await firstItem.click();
  const mobileApp=await page.locator('.lf-app.lf-student').boundingBox();
  const mobileOverlay=await page.locator('.lf-overlay').boundingBox();
  const mobileDialog=await page.getByRole('dialog',{name:'拾得物の詳細'}).boundingBox();
  await expect(page.getByRole('dialog',{name:'拾得物の詳細'})).toContainText('受付番号 #1');
  expect(Math.abs(mobileOverlay!.x-mobileApp!.x)).toBeLessThanOrEqual(1);
  expect(Math.abs(mobileOverlay!.y-mobileApp!.y)).toBeLessThanOrEqual(1);
  expect(Math.abs(mobileOverlay!.width-mobileApp!.width)).toBeLessThanOrEqual(1);
  expect(Math.abs(mobileOverlay!.height-mobileApp!.height)).toBeLessThanOrEqual(1);
  expect(Math.abs((mobileDialog!.y+mobileDialog!.height)-(mobileApp!.y+mobileApp!.height-12))).toBeLessThanOrEqual(1);
  await page.getByRole('dialog').getByRole('button',{name:'閉じる',exact:true}).click();
  await expect(page.getByRole('heading',{name:'落とし物を探す'})).toHaveCount(0);
  await expect(page.getByRole('button',{name:'検索',exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:'絞り込み'}).click();
  await page.getByRole('button',{name:'白',exact:true}).click();
  await page.getByRole('button',{name:'この条件で探す'}).click();
  await expect(page.getByRole('heading',{name:'長傘',exact:true})).toBeVisible();
  await expect(page.getByRole('heading',{name:'ペンケース',exact:true})).toHaveCount(0);
  await expect(page.getByRole('button',{name:'紛失申告を登録'})).toHaveCount(1);
  await expect(page.locator('body')).toHaveJSProperty('scrollWidth',390);
  await page.screenshot({path:'temp/screenshots/student-mobile.png',fullPage:true});
  await page.getByRole('button',{name:'絞り込み'}).click();
  await page.getByRole('combobox',{name:'種類',exact:true}).selectOption('P05');
  await page.getByRole('combobox',{name:'細かい種類',exact:true}).selectOption('P05_UMBRELLA_FOLDING');
  await page.getByRole('button',{name:'この条件で探す'}).click();
  // The empty-state action must be visible before clicking can scroll it into view.
  await page.setViewportSize({width:375,height:667});
  await page.evaluate(()=>window.scrollTo(0,0));
  const notifyButton=page.getByRole('button',{name:'紛失申告を登録'});
  await expect(notifyButton).toBeInViewport({ratio:1});
  const notifyBox=await notifyButton.boundingBox();
  const navBox=await page.getByRole('navigation',{name:'学生メニュー'}).boundingBox();
  expect(notifyBox!.y+notifyBox!.height).toBeLessThanOrEqual(navBox!.y);
  await page.screenshot({path:'temp/screenshots/student-empty-mobile.png'});
  await notifyButton.click();
  await page.setViewportSize({width:390,height:844});
  await page.getByRole('dialog').getByLabel('特徴（任意）').fill('ケースの裏に青いシール');
  await page.getByRole('dialog').getByRole('button',{name:'紛失申告を登録',exact:true}).click();
  await expect(page.getByText('紛失申告を登録しました。条件に合う候補が見つかるとお知らせします。')).toBeVisible();
  const staff=await context.newPage();await staff.setViewportSize({width:1440,height:1000});await staff.goto('/?role=staff');
  await staff.getByRole('navigation',{name:'職員メニュー'}).getByRole('button',{name:'学生の紛失申告',exact:true}).click();
  await expect(staff.getByText('ケースの裏に青いシール')).toBeVisible();
  await expect(staff.getByText('非公開品と照合',{exact:true})).toBeVisible();
  await expect(staff.locator('.lf-item-card')).toBeEnabled();
  await staff.getByRole('navigation',{name:'職員メニュー'}).getByRole('button',{name:'保管中の拾得物',exact:true}).click();
  await staff.getByRole('button',{name:'＋ 拾得物を登録'}).click();
  await expect(staff.getByLabel('保管場所（必須）')).toHaveValue('農学部事務室');
  await staff.getByRole('combobox',{name:'種類（必須）',exact:true}).selectOption('P05');await staff.getByRole('combobox',{name:'細かい種類（必須）',exact:true}).selectOption('P05_UMBRELLA_FOLDING');
  await staff.getByRole('combobox',{name:'拾得キャンパス（必須）',exact:true}).selectOption('C02');
  await staff.getByRole('button',{name:'白',exact:true}).click();await staff.getByRole('button',{name:'青',exact:true}).click();
  await staff.getByRole('button',{name:'拾得物を登録',exact:true}).last().click();
  await expect(staff.getByText('拾得物を登録しました。')).toBeVisible();
  await staff.getByRole('navigation',{name:'職員メニュー'}).getByRole('button',{name:'保管中の拾得物'}).click();
  await staff.screenshot({path:'temp/screenshots/staff-desktop.png',fullPage:true});
  await staff.getByRole('button',{name:'メニューを閉じる',exact:true}).click();await expect(staff.locator('.lf-app')).toHaveClass(/lf-collapsed/);
  await page.bringToFront();await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await page.getByRole('navigation',{name:'学生メニュー'}).getByRole('button',{name:'お知らせ'}).click();
  await page.getByRole('button',{name:'候補の詳細を見る'}).click();await page.getByRole('dialog').getByRole('button',{name:'自分のものだと思う'}).click();await page.getByRole('dialog').getByRole('button',{name:'受け取りを申し込む'}).click();
  await expect(page.getByRole('heading',{name:'受け取り予定',exact:true})).toHaveCount(0);
  await expect(page.getByRole('heading',{name:'折りたたみ傘',exact:true})).toBeVisible();
  await expect(page.getByText(/CLM-/)).toHaveCount(0);
  await staff.getByRole('button',{name:'メニューを開く'}).click();await staff.bringToFront();await staff.evaluate(()=>window.dispatchEvent(new Event('focus')));await staff.getByRole('navigation',{name:'職員メニュー'}).getByRole('button',{name:'保管中の拾得物'}).click();
  await expect(staff.getByRole('combobox',{name:'表示する保管窓口'})).toHaveValue('own');
  await expect(staff.getByText(/CLM-/)).toHaveCount(0);
  await staff.getByRole('navigation',{name:'職員メニュー'}).getByRole('button',{name:'保管中の拾得物',exact:true}).click();
  await expect(staff.getByText('↩ 受取希望あり',{exact:true})).toHaveCount(1);
  await staff.getByRole('button',{name:'絞り込み',exact:true}).click();
  await staff.getByRole('combobox',{name:'受取希望',exact:true}).selectOption('pending');
  await expect(staff.locator('.lf-item-card')).toHaveCount(1);
  const itemNumber=(await staff.locator('.lf-item-card .lf-card-meta span').first().innerText()).replace('#','');
  await staff.getByRole('textbox',{name:'拾得物を検索',exact:true}).fill(itemNumber);
  await staff.locator('.lf-item-card').click();
  await staff.getByRole('button',{name:'返却する',exact:true}).click();
  await expect(staff.getByRole('dialog',{name:'本人確認・返却記録'})).toBeVisible();
  await expect(staff.getByRole('button',{name:'← 詳細へ戻る'})).toHaveCount(0);
  await expect(staff.getByText('ケースの裏に青いシール')).toBeVisible();await expect(staff.getByRole('button',{name:'返却済みにする'})).toBeDisabled();
  await staff.getByRole('checkbox',{name:'現物と申告内容を確認し、本人確認を完了しました'}).check();await staff.getByRole('button',{name:'返却済みにする'}).click();
  await expect(staff.getByText('返却を記録しました。')).toBeVisible();
  await page.bringToFront();await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await page.getByRole('navigation',{name:'学生メニュー'}).getByRole('button',{name:'履歴',exact:true}).click();
  await page.getByRole('button',{name:'感謝の一言を残す（任意）'}).click();await page.getByRole('textbox').fill('見つかってよかったです。ありがとう！');await page.getByRole('button',{name:'一言を送る'}).click();
  await expect(page.getByText('感謝の一言を受け付けました。公開反映までお待ちください。')).toBeVisible();
});
test('学生は公開区分を選ばず、一覧に出ない物も同じ申告として登録する',async({page})=>{
  await page.setViewportSize({width:375,height:812});await page.goto('/?role=student');
  await page.getByRole('navigation',{name:'学生メニュー'}).getByRole('button',{name:'探す',exact:true}).click();
  const appBox=await page.locator('.lf-app').boundingBox();
  const firstCardBox=await page.locator('.lf-item-card').first().boundingBox();
  expect(firstCardBox!.y-appBox!.y).toBeLessThanOrEqual(220);
  expect((await page.getByRole('button',{name:'絞り込み',exact:true}).boundingBox())!.height).toBeGreaterThanOrEqual(44);
  await expect(page.getByRole('note')).toHaveCount(0);
  await expect(page.getByText('絞り込み後、候補に自分の物がなければ、紛失申告を登録できます。')).toBeVisible();
  await expect(page.getByRole('button',{name:'紛失申告を登録'})).toHaveCount(0);
  await expect(page.getByRole('button',{name:'条件を入力する',exact:true})).toHaveCount(0);
  await expect(page.getByRole('button',{name:'絞り込み',exact:true})).toHaveCount(1);
  await page.getByRole('button',{name:'絞り込み',exact:true}).click();
  await expect(page.getByRole('dialog',{name:'検索条件'})).toBeVisible();
  await expect(page.getByRole('combobox',{name:'建物・エリア',exact:true})).toHaveCount(0);
  await page.getByRole('dialog').getByRole('combobox',{name:'種類',exact:true}).selectOption('P04');
  await page.getByRole('dialog').getByRole('combobox',{name:'細かい種類',exact:true}).selectOption('P04_WATCH');
  await page.getByRole('dialog').getByRole('button',{name:'この条件で探す'}).click();
  await expect(page.getByText('この条件に合う公開中の拾得物はありません。')).toBeVisible();
  await page.getByRole('button',{name:'紛失申告を登録'}).click();
  await expect(page.getByText('紛失した物の種類・色・場所・日付・特徴を申告します。条件に合う候補が見つかるとお知らせします。公開一覧に出ない品物は職員が確認します。')).toBeVisible();

  await page.getByRole('dialog').getByRole('button',{name:'紛失申告を登録',exact:true}).click();
  await expect(page.getByText('紛失申告を登録しました。条件に合う候補が見つかるとお知らせします。')).toBeVisible();
  await expect(page.getByText('紛失した物の種類・色・場所・日付・特徴を申告できます。登録した条件に合う候補が見つかるとお知らせします。')).toBeVisible();
  await page.getByRole('button',{name:'別の紛失申告を登録',exact:true}).click();
  await expect(page.getByRole('dialog').getByRole('combobox',{name:'種類',exact:true})).toHaveValue('');
  const db=await page.evaluate(()=>JSON.parse(localStorage.getItem('lost-found-no-qr-test-harness-v1')!));
  expect(db.requests[0].value).toMatchObject({valuable:false,criteria:{category:'P04_WATCH'}});
});

test('財布も共通の登録ボタンから保存でき、職員が非公開の現物と照合できる',async({page,context})=>{
  await page.setViewportSize({width:320,height:667});
  await page.goto('/?role=student');
  await page.getByRole('navigation',{name:'学生メニュー'}).getByRole('button',{name:'探す',exact:true}).click();
  await page.getByRole('button',{name:'絞り込み',exact:true}).click();
  await page.getByRole('combobox',{name:'種類',exact:true}).selectOption('P01');
  await page.getByRole('combobox',{name:'細かい種類',exact:true}).selectOption('P01_WALLET');
  await page.getByRole('combobox',{name:'キャンパス',exact:true}).selectOption('C02');
  await page.getByRole('button',{name:'この条件で探す'}).click();
  const register=page.getByRole('button',{name:'紛失申告を登録',exact:true});
  await expect(register).toHaveCount(1);
  await expect(register).toBeInViewport({ratio:1});
  await expect(page.getByText('候補に自分の物がなければ、この検索条件で紛失申告を登録し、通知を待てます。')).toBeVisible();
  await expect(page.locator('.lf-item-card')).toHaveCount(0);
  await expect(page.locator('body')).toHaveJSProperty('scrollWidth',320);
  await page.screenshot({path:'temp/screenshots/student-wallet-register.png'});
  await register.click();
  const form=page.getByRole('dialog');
  await expect(form.getByRole('combobox',{name:'細かい種類',exact:true})).toHaveValue('P01_WALLET');
  await expect(form.getByRole('combobox',{name:'キャンパス',exact:true})).toHaveValue('C02');
  await form.getByLabel('特徴（任意）').fill('内側のポケットに星のシール');

  await page.getByRole('dialog').getByRole('button',{name:'紛失申告を登録',exact:true}).click();
  await expect(page.getByText('紛失申告を登録しました。条件に合う候補が見つかるとお知らせします。')).toBeVisible();
  const db=await page.evaluate(()=>JSON.parse(localStorage.getItem('lost-found-no-qr-test-harness-v1')!));
  expect(db.requests).toHaveLength(1);
  expect(db.requests[0].value).toMatchObject({status:'ACTIVE',valuable:false,criteria:{parent:'P01',category:'P01_WALLET',campus:'C02'}});
  expect(db.notices).toHaveLength(0);
  const staff=await context.newPage();
  await staff.setViewportSize({width:1440,height:900});
  await staff.goto('/?role=staff');
  await staff.getByRole('navigation',{name:'職員メニュー'}).getByRole('button',{name:'学生の紛失申告',exact:true}).click();
  await staff.getByRole('button',{name:/内側のポケットに星のシール/}).click();
  const review=staff.getByRole('dialog',{name:'紛失申告と非公開品を照合'});
  await expect(review).toContainText('内側のポケットに星のシール');
  await expect(review.locator('.lf-item-card').getByRole('heading',{name:'財布',exact:true})).toBeVisible();
});

test('同じ腕時計でも品物ごとの公開設定を反映し、非公開の時計を共通の申告から探せる',async({page,context})=>{
  await page.setViewportSize({width:375,height:667});
  await page.goto('/?role=student');
  await page.getByRole('navigation',{name:'学生メニュー'}).getByRole('button',{name:'探す',exact:true}).click();
  await page.getByRole('button',{name:'絞り込み',exact:true}).click();
  await page.getByRole('combobox',{name:'種類',exact:true}).selectOption('P04');
  await page.getByRole('combobox',{name:'細かい種類',exact:true}).selectOption('P04_WATCH');
  await page.getByRole('button',{name:'この条件で探す'}).click();
  await page.getByRole('button',{name:'紛失申告を登録',exact:true}).click();
  await page.getByRole('dialog').getByLabel('特徴（任意）').fill('留め具に星の刻印');

  await page.getByRole('dialog').getByRole('button',{name:'紛失申告を登録',exact:true}).click();
  await expect(page.getByText('紛失申告を登録しました。条件に合う候補が見つかるとお知らせします。')).toBeVisible();
  await page.evaluate(()=>{const key='lost-found-no-qr-test-harness-v1';const db=JSON.parse(localStorage.getItem(key)!);db.requests[0].value.createdAt='2000-01-01T00:00:00.000Z';localStorage.setItem(key,JSON.stringify(db));});
  const staff=await context.newPage();await staff.goto('/?role=staff');
  for(const privateItem of [true,false]) {
    await staff.getByRole('button',{name:'＋ 拾得物を登録'}).click();
    await staff.getByRole('combobox',{name:'種類（必須）',exact:true}).selectOption('P04');
    await staff.getByRole('combobox',{name:'細かい種類（必須）',exact:true}).selectOption('P04_WATCH');
    await staff.getByRole('combobox',{name:'拾得キャンパス（必須）',exact:true}).selectOption('C02');
    await staff.getByLabel('特徴（任意）').fill(privateItem?'非公開の刻印付き時計':'公開の丸い文字盤の時計');
    await staff.getByRole('checkbox',{name:'学生一覧に公開しない（高価な物など）'}).setChecked(privateItem);
    await staff.getByRole('button',{name:'拾得物を登録',exact:true}).click();
    await expect(staff.getByText('拾得物を登録しました。')).toBeVisible();
    await page.reload();
    await page.getByRole('textbox',{name:'キーワードで探す'}).fill('腕時計');
    await expect(page.getByRole('heading',{name:privateItem?'公開中の拾得物 0件':'公開中の拾得物 1件',exact:true})).toBeVisible();
    await expect(page.getByText('絞り込み後、候補に自分の物がなければ、紛失申告を登録できます。')).toBeVisible();
    await expect(page.getByRole('button',{name:'紛失申告を登録',exact:true})).toHaveCount(0);
    await expect(page.getByText(/非公開の刻印付き時計/)).toHaveCount(0);
    const db=await page.evaluate(()=>JSON.parse(localStorage.getItem('lost-found-no-qr-test-harness-v1')!));
    expect(db.notices).toHaveLength(privateItem?0:1);
    if(privateItem) {
      await expect(page.getByText('この条件に合う公開中の拾得物はありません。')).toBeVisible();
      await page.screenshot({path:'temp/screenshots/student-private-watch.png'});
      await staff.getByRole('navigation',{name:'職員メニュー'}).getByRole('button',{name:'学生の紛失申告',exact:true}).click();
      await staff.getByRole('button',{name:/留め具に星の刻印/}).click();
      const review=staff.getByRole('dialog',{name:'紛失申告と非公開品を照合'});
      await expect(review).toContainText('非公開の刻印付き時計');
      await review.getByRole('button',{name:'閉じる',exact:true}).click();
      await staff.getByRole('navigation',{name:'職員メニュー'}).getByRole('button',{name:'保管中の拾得物',exact:true}).click();
    } else {
      await expect(page.getByText(/公開の丸い文字盤の時計/)).toBeVisible();
      expect(db.notices[0].value.kind).toBe('MATCH');
    }
  }
});

test('所属窓口を初期表示し、登録導線は一つ、メニューを閉じるとタブを隠す',async({page})=>{
 await page.setViewportSize({width:1440,height:1000});await page.goto('/?role=staff');
 await expect(page.getByRole('combobox',{name:'表示する保管窓口'})).toHaveValue('own');
 await expect(page.getByRole('navigation',{name:'職員メニュー'}).getByRole('button',{name:'拾得物を登録'})).toHaveCount(0);
 await expect(page.getByRole('button',{name:'＋ 拾得物を登録'})).toHaveCount(1);
 await page.getByRole('navigation',{name:'職員メニュー'}).getByRole('button',{name:'利用者設定'}).click();
 await page.getByLabel('いつもの保管窓口').fill('工学部事務室');await page.getByRole('button',{name:'保存する',exact:true}).click();
 await page.getByRole('navigation',{name:'職員メニュー'}).getByRole('button',{name:'保管中の拾得物'}).click();await expect(page.locator('.lf-item-card')).toHaveCount(0);
 await page.getByRole('combobox',{name:'表示する保管窓口'}).selectOption('all');
 await expect(page.locator('.lf-item-card')).not.toHaveCount(0);
 await page.locator('.lf-item-card').first().click();
 await expect(page.getByRole('button',{name:'返却する',exact:true})).toBeDisabled();
 await page.getByRole('dialog').getByRole('button',{name:'閉じる',exact:true}).click();
 await expect(page.getByRole('navigation',{name:'職員メニュー'}).getByRole('button',{name:'返却対応',exact:true})).toHaveCount(0);
 await expect(page.getByRole('combobox',{name:'表示する保管窓口'})).toHaveValue('all');
 await page.getByRole('navigation',{name:'職員メニュー'}).getByRole('button',{name:'保管中の拾得物',exact:true}).click();
 await expect(page.getByRole('combobox',{name:'表示する保管窓口'})).toHaveValue('own');
 await page.getByRole('button',{name:'メニューを閉じる'}).click();await expect(page.getByRole('navigation',{name:'職員メニュー'})).toHaveCount(0);
 await page.getByRole('button',{name:'メニューを開く'}).click();await expect(page.getByRole('navigation',{name:'職員メニュー'})).toBeVisible();
});

test('検索条件はモーダルで確定し、キャンセル時には検索に反映しない',async({page})=>{
 await page.setViewportSize({width:375,height:812});await page.goto('/?role=student');
 await expect(page.getByRole('button',{name:'紛失申告を登録'})).toHaveCount(0);
 await page.getByRole('textbox',{name:'キーワードで探す'}).press('Enter');
 await expect(page.getByRole('button',{name:'解除',exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'絞り込み'}).click();
 await page.getByRole('button',{name:'この条件で探す'}).click();
 await expect(page.getByRole('button',{name:'解除',exact:true})).toHaveCount(0);
 await page.getByRole('textbox',{name:'キーワードで探す'}).fill('傘');
 await expect(page.getByRole('button',{name:'解除',exact:true})).toBeVisible();
 await expect(page.getByText('紛失申告を登録して、届いたら通知。')).toHaveCount(0);
 await expect(page.getByRole('button',{name:'紛失申告を登録'})).toHaveCount(0);
 await expect(page.getByRole('button',{name:'条件を入力する',exact:true})).toHaveCount(0);
 await expect(page.getByRole('heading',{name:'ペンケース',exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'解除',exact:true}).click();
 await expect(page.getByRole('button',{name:'解除',exact:true})).toHaveCount(0);
 await expect(page.getByRole('button',{name:'条件を入力する',exact:true})).toHaveCount(0);
 await expect(page.getByRole('region',{name:'見つからない物の通知'})).toContainText('絞り込み後、候補に自分の物がなければ、紛失申告を登録できます。');
 await page.getByRole('button',{name:'絞り込み'}).click();
 await expect(page.getByRole('dialog',{name:'検索条件'})).toBeVisible();
  await expect(page.getByRole('combobox',{name:'建物・エリア',exact:true})).toHaveCount(0);
 await page.getByRole('combobox',{name:'種類',exact:true}).selectOption('P01');
 await page.screenshot({path:'temp/screenshots/student-filters.png',fullPage:true});
 await page.getByRole('button',{name:'閉じる',exact:true}).click();
 await expect(page.getByRole('heading',{name:'長傘',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'絞り込み'}).click();
 await expect(page.getByRole('combobox',{name:'種類',exact:true})).toHaveValue('');
 await page.getByRole('combobox',{name:'種類',exact:true}).selectOption('P01');await page.getByRole('button',{name:'この条件で探す'}).click();
 await expect(page.getByText('この条件に合う公開中の拾得物はありません。')).toBeVisible();
 await expect(page.getByRole('button',{name:'紛失申告を登録'})).toHaveCount(1);
 await expect(page.getByRole('region',{name:'見つからない物の通知'}).getByRole('button',{name:'紛失申告を登録'})).toBeInViewport({ratio:1});
 await expect(page.locator('.lf-item-card')).toHaveCount(0);
 await expect(page.locator('body')).toHaveJSProperty('scrollWidth',375);
});

test('職員一覧の種類・キャンパス・複数色を持つ品物の色絞り込み',async({page})=>{
 await page.setViewportSize({width:1440,height:1000});await page.goto('/?role=staff');
 await expect(page.getByText('一覧に公開',{exact:true}).first()).toBeVisible();
 await expect(page.getByText('学生への公開：',{exact:false})).toHaveCount(0);
 await page.getByRole('button',{name:'絞り込み',exact:true}).click();
 const filters=page.getByRole('region',{name:'拾得物の絞り込み'});
 await filters.getByRole('combobox',{name:'色',exact:true}).selectOption('白');
 await expect(page.getByRole('heading',{name:'長傘',exact:true})).toBeVisible();
 await expect(page.getByRole('heading',{name:'財布',exact:true})).toHaveCount(0);
 await filters.getByRole('combobox',{name:'種類',exact:true}).selectOption('P05');
 await expect(page.locator('.lf-item-card')).toHaveCount(1);
 await filters.getByRole('combobox',{name:'拾得キャンパス',exact:true}).selectOption('C08');await expect(page.locator('.lf-item-card')).toHaveCount(0);
 await filters.getByRole('button',{name:'条件を解除'}).click();await expect(page.locator('.lf-item-card')).toHaveCount(5);
 const card=page.locator('.lf-item-card').first();await card.locator('h3').hover();
 await expect(card).toHaveCSS('background-color','rgb(239, 239, 239)');
 await page.screenshot({path:'temp/screenshots/staff-filters.png',fullPage:true});
 await page.getByRole('button',{name:'＋ 拾得物を登録'}).click();
 await expect(page.getByRole('combobox',{name:'細かい種類（必須）',exact:true})).toHaveAttribute('required','');
 await expect(page.getByRole('combobox',{name:'拾得キャンパス（必須）',exact:true})).toHaveAttribute('required','');
});

test('複数の申告は返却モーダルで選び、相手を変えたら本人確認をやり直す',async({page})=>{
 await page.goto('/?role=staff');
 await page.evaluate(()=>{
   const key='lost-found-no-qr-test-harness-v1';const db=JSON.parse(localStorage.getItem(key)!);
   db.profiles.push(...['a','b'].map((x,i)=>({id:String(90+i),author:x,etag:'1',value:{name:'学生'+x,email:'student'+i+'@stu.kobe-u.ac.jp'}})));
   db.claims=['a','b'].map((x,i)=>({id:String(90+i),author:x,etag:'1',value:{itemId:'1',status:'PENDING',feature:'特徴'+x,title:'長傘',window:'農学部事務室',createdAt:new Date().toISOString()}}));
   localStorage.setItem(key,JSON.stringify(db));
 });
 await page.reload();await page.getByRole('button',{name:/長傘/}).click();await page.getByRole('button',{name:'返却する',exact:true}).click();
 const dialog=page.getByRole('dialog');const recipient=dialog.getByRole('combobox',{name:'返却する相手'});const check=dialog.getByRole('checkbox');
 await expect(recipient).toHaveValue('');await expect(check).toBeDisabled();
 await recipient.selectOption('90');await expect(dialog.getByText('特徴a',{exact:true})).toBeVisible();await check.check();
 await recipient.selectOption('91');await expect(check).not.toBeChecked();await expect(dialog.getByText('特徴b',{exact:true})).toBeVisible();
 await expect(dialog.getByLabel('返却先の学校メール（学籍番号付き）')).toHaveValue('student1@stu.kobe-u.ac.jp');
 await check.check();await recipient.selectOption('walkin');await expect(check).not.toBeChecked();
 await expect(dialog.getByLabel('返却先の学校メール（学籍番号付き）')).toHaveValue('');
 await dialog.getByLabel('返却先の学校メール（学籍番号付き）').fill('visitor123@stu.kobe-u.ac.jp');await check.check();await dialog.getByRole('button',{name:'返却済みにする'}).click();
 const db=await page.evaluate(()=>JSON.parse(localStorage.getItem('lost-found-no-qr-test-harness-v1')!));
 expect(db.items.find((r:{id:string})=>r.id==='1').value).toMatchObject({claimId:'',recipientEmail:'visitor123@stu.kobe-u.ac.jp',status:'返却済み'});
 expect(db.claims).toHaveLength(2);
});

test('通常に登録した申告からも同じ画面で非公開品を選び、現物確認後に案内する',async({page})=>{
 await page.goto('/?role=staff');
 await page.evaluate(()=>{const key='lost-found-no-qr-test-harness-v1';const db=JSON.parse(localStorage.getItem(key)!);db.profiles.push({id:'91',author:'student-search',etag:'1',value:{email:'s269999@stu.kobe-u.ac.jp',window:''}});db.requests=[{id:'91',author:'student-search',etag:'1',value:{criteria:{parent:'P01',category:'P01_WALLET',colors:['黒'],campus:'',building:'',dateFrom:'',dateTo:'',query:''},feature:'内側にイニシャル',valuable:false,status:'ACTIVE',createdAt:new Date().toISOString()}}];localStorage.setItem(key,JSON.stringify(db));});
 await page.reload();await page.getByRole('navigation',{name:'職員メニュー'}).getByRole('button',{name:'学生の紛失申告',exact:true}).click();
 const requestSearch=page.getByRole('textbox',{name:'学生の紛失申告を検索'});await requestSearch.fill('s260000');await expect(page.locator('.lf-item-grid .lf-item-card')).toHaveCount(0);await requestSearch.fill('s269999');const requestCard=page.locator('.lf-item-grid .lf-item-card');await expect(requestCard).toHaveCount(1);await expect(requestCard).toContainText('学籍番号：s269999');await requestSearch.fill('');
 await expect(page.getByText('公開区分は拾得物側で判断します。申告を開くと、非公開・保管中の拾得物だけを照合できます。')).toBeVisible();
 await expect(page.locator('.lf-item-grid .lf-item-card')).toHaveCount(1);await expect(page.getByText('非公開品と照合',{exact:true})).toBeVisible();await page.locator('.lf-item-card').click();
 const dialog=page.getByRole('dialog',{name:'紛失申告と非公開品を照合'});await expect(dialog).toBeVisible();await expect(dialog.getByRole('combobox',{name:'保管窓口',exact:true})).toHaveValue('own');
 await expect(dialog.getByRole('combobox',{name:'保管品の種類',exact:true})).toHaveValue('all');const wallet=dialog.locator('.lf-item-card').filter({hasText:'#4'});await expect(wallet).toBeVisible();await wallet.click();await expect(dialog.getByRole('button',{name:'この品物で本人へ案内'})).toBeDisabled();
 await dialog.getByRole('checkbox').check();await expect(dialog.getByRole('button',{name:'この品物で本人へ案内'})).toBeEnabled();
 await dialog.getByRole('combobox',{name:'保管品の種類',exact:true}).selectOption('same');await expect(dialog.getByRole('checkbox')).not.toBeChecked();await expect(dialog.getByRole('button',{name:'この品物で本人へ案内'})).toBeDisabled();
 await dialog.getByRole('combobox',{name:'保管品の種類',exact:true}).selectOption('all');await wallet.click();await dialog.getByRole('checkbox').check();await dialog.getByRole('button',{name:'この品物で本人へ案内'}).click();await expect(page.getByText('本人への案内を登録しました。')).toBeVisible();
 const db=await page.evaluate(()=>JSON.parse(localStorage.getItem('lost-found-no-qr-test-harness-v1')!));expect(db.notices).toHaveLength(1);expect(db.notices[0].value).toMatchObject({itemId:'4',requestId:'91'});
});

test('絞り込み後は候補があっても違う物として登録できる',async({page})=>{
  await page.goto('/?role=student');
  const register=page.getByRole('button',{name:'紛失申告を登録',exact:true});
  await expect(register).toHaveCount(0);
  await page.getByRole('textbox',{name:'キーワードで探す'}).fill('存在しない物');
  await expect(register).toHaveCount(0);
  await page.getByRole('button',{name:'解除',exact:true}).click();
  await page.getByRole('button',{name:'絞り込み',exact:true}).click();
  await page.getByRole('combobox',{name:'種類',exact:true}).selectOption('P05');
  await page.getByRole('button',{name:'この条件で探す'}).click();
  await expect(page.getByRole('heading',{name:'長傘',exact:true})).toBeVisible();
  await expect(register).toHaveCount(1);
  await expect(page.getByText('候補に自分の物がなければ、この検索条件で紛失申告を登録し、通知を待てます。')).toBeVisible();
  await register.click();
  const dialog=page.getByRole('dialog');
  await expect(dialog.getByRole('button',{name:'紛失申告を登録'})).toBeEnabled();
  await dialog.getByLabel('特徴（任意）').fill('一覧の長傘とは違う持ち手');
  await dialog.getByRole('button',{name:'紛失申告を登録'}).click();
  await expect(page.getByText('紛失申告を登録しました。条件に合う候補が見つかるとお知らせします。')).toBeVisible();
  const db=await page.evaluate(()=>JSON.parse(localStorage.getItem('lost-found-no-qr-test-harness-v1')!));
  expect(db.requests[0].value).toMatchObject({status:'ACTIVE',feature:'一覧の長傘とは違う持ち手',criteria:{parent:'P05'}});
});

test('通知を待っている物は各項目の意味を表示し、新しい順で取り下げられる',async({page})=>{
  await page.goto('/?role=student');
  await page.evaluate(()=>{
    const key='lost-found-no-qr-test-harness-v1';const db=JSON.parse(localStorage.getItem(key)!);
    const owner='student-1';
    db.requests=[['81','2026-09-01T00:00:00Z','古い登録'],['82','2026-09-02T00:00:00Z','新しい登録']].map(([id,createdAt,feature])=>({id,author:owner,etag:'1',value:{criteria:{parent:'P05',category:'',colors:[],campus:'',building:'',dateFrom:'',dateTo:'',query:''},feature,valuable:false,status:'ACTIVE',createdAt}}));
    localStorage.setItem(key,JSON.stringify(db));
  });
  await page.reload();await page.getByRole('navigation',{name:'学生メニュー'}).getByRole('button',{name:'登録・受取'}).click();
  await expect(page.getByRole('heading',{name:'紛失申告',exact:true})).toHaveCount(0);
  const cards=page.locator('article.lf-panel');
  await expect(cards).toHaveCount(2);await expect(cards.first()).toContainText('新しい登録');
  await expect(cards.first()).not.toContainText('登録 #82');
  await expect(cards.first().getByText('種類',{exact:true})).toBeVisible();
  await expect(cards.first().getByText('色',{exact:true})).toBeVisible();
  await expect(cards.first().getByText('キャンパス・場所',{exact:true})).toBeVisible();
  await expect(cards.first().getByText('なくした時期',{exact:true})).toBeVisible();
  await expect(cards.first().getByText('特徴',{exact:true})).toBeVisible();
  page.on('dialog',d=>d.accept());
  await cards.first().getByRole('button',{name:'取り下げ',exact:true}).click();
  await expect(cards).toHaveCount(1);await expect(cards.first()).toContainText('古い登録');
  await cards.first().getByRole('button',{name:'取り下げ',exact:true}).click();
  await expect(cards).toHaveCount(0);await expect(page.getByText('登録した紛失申告はありません')).toBeVisible();
});
