import assert from 'node:assert/strict';
import {SharePointRepository} from '../src/webparts/lostFoundStudent/app/repositories';
import {StudentService} from '../src/webparts/lostFoundStudent/app/service';
import {emptyCriteria,matches,matchesRequest,splitColors,studentIdFromEmail,today,validateSchoolEmail} from '../src/webparts/lostFoundStudent/app/model';
import {DemoRepository,DEMO_STAFF,DEMO_STUDENT} from './support/DemoRepository';
import {WorkflowService} from './support/WorkflowService';
const denied=new SharePointRepository({get:async()=>({ok:false,status:403})} as any,'https://example.invalid',DEMO_STUDENT);
const storage=new Map<string,string>();
Object.defineProperty(globalThis,'localStorage',{value:{getItem:(k:string)=>storage.get(k)||null,setItem:(k:string,v:string)=>storage.set(k,v)}});
async function test():Promise<void>{
assert.deepEqual(await denied.list('notices'),[],'最初の通知を受け取る前でも学生画面を開ける');
await assert.rejects(()=>denied.list('public'),'公開一覧の権限エラーは隠さない');
const student=new StudentService(new DemoRepository({...DEMO_STUDENT}));
const readTables:string[]=[]; const previewRepo=new DemoRepository({...DEMO_STUDENT,role:'staff'}); const read=previewRepo.list.bind(previewRepo);
previewRepo.list=async table=>{readTables.push(table);return read(table);};
await new StudentService(previewRepo).load();
assert(!readTables.includes('items') && !readTables.includes('mail'),'学生サービスは職員アカウントでも非公開リストを読まない');
assert(!('returnItem' in student) && !('saveItem' in student),'学生サービスには職員の更新操作を含めない');
const staff=new WorkflowService(new DemoRepository({...DEMO_STAFF}));
let data=await student.load();assert(!data.items.some(i=>i.valuable));assert.equal(data.items.length,4);
const umbrella=data.items.find(i=>i.id==='1')!;
assert(matches(umbrella,{...emptyCriteria(),colors:['白','青']}));assert(!matches(umbrella,{...emptyCriteria(),colors:['青']}));assert.deepEqual(splitColors('黒;白、黒'),['黒','白']);
assert(matchesRequest({...umbrella,feature:'青い ABC シール'},{id:'query-test',owner:'x',email:DEMO_STUDENT.email,criteria:{...emptyCriteria(),parent:'P05',query:'ABC　シール'},feature:'',valuable:false,status:'ACTIVE',createdAt:''}));
assert(!matchesRequest({...umbrella,feature:'無地'},{id:'query-test',owner:'x',email:DEMO_STUDENT.email,criteria:{...emptyCriteria(),parent:'P05',query:'ABC シール'},feature:'',valuable:false,status:'ACTIVE',createdAt:''}));
assert.throws(()=>validateSchoolEmail('x@evil.example',['stu.kobe-u.ac.jp']));
assert.equal(studentIdFromEmail('S260001@stu.kobe-u.ac.jp'),'s260001');
await student.saveRequest({...emptyCriteria(),parent:'P05',colors:['白']},'左に傷');
await staff.reconcile();assert.equal((await student.load()).notices.length,0,'条件保存時・再同期時に遡及照合しない');
await new Promise(r=>setTimeout(r,5));
await assert.rejects(()=>staff.saveItem({parent:'P05',category:'',title:'傘',colors:[],campus:'C02',building:'',place:'',foundOn:today(),window:'農学部事務室',feature:'',valuable:false}),/細かい種類/);
await assert.rejects(()=>staff.saveItem({parent:'P05',category:'P05_UMBRELLA_LONG',title:'傘',colors:[],campus:'',building:'',place:'',foundOn:today(),window:'農学部事務室',feature:'',valuable:false}),/拾得キャンパス/);
await staff.saveItem({parent:'P05',category:'P05_UMBRELLA_LONG',title:'長傘',colors:['白','黒'],campus:'C02',building:'',place:'農学部',foundOn:today(),window:'農学部事務室',feature:'木の持ち手',valuable:false});
data=await student.load();assert.equal(data.notices.length,1);const notice=data.notices[0];
await staff.reconcile();assert.equal((await student.load()).notices.length,1,'通知は重複しない');
await student.createClaim(notice.itemId,'',notice.requestId);data=await student.load();const claim=data.claims[0];assert.equal(claim.feature,'左に傷');
await assert.rejects(()=>staff.returnItem(notice.itemId,claim.email,claim.id,false));
for(const window of ['工学部事務室','']) {
  await staff.saveProfile({email:DEMO_STAFF.email,window});
  await assert.rejects(()=>staff.returnItem(notice.itemId,claim.email,claim.id,true),/所属窓口/);
  await assert.rejects(()=>staff.returnItem('1',DEMO_STUDENT.email,'',true),/所属窓口/);
  assert.equal((await staff.load()).items.find(i=>i.id===notice.itemId)!.status,'保管中');
}
await staff.saveProfile({email:DEMO_STAFF.email,window:'農学部事務室'});
await staff.returnItem(notice.itemId,claim.email,claim.id,true);
await assert.rejects(()=>staff.returnItem(notice.itemId,claim.email,claim.id,true),'二重返却を拒否');
data=await student.load();assert(!data.items.some(i=>i.id===notice.itemId));assert(data.notices.some(n=>n.kind==='RETURN'));assert.equal(data.requests[0].status,'RESOLVED');
await student.saveThanks(claim.id,'ありがとうございました');await staff.reconcile();assert.equal((await student.load()).thanks[0].message,'ありがとうございました');
await student.saveRequest({...emptyCriteria(),parent:'P01',category:'P01_WALLET'},'右下に傷');const valuable=(await student.load()).requests.find(r=>r.criteria.parent==='P01')!;
await staff.notify('4',valuable.id);data=await student.load();const privateNotice=data.notices.find(n=>n.kind==='VALUABLE')!;assert(privateNotice);assert(!JSON.stringify(privateNotice).includes('二つ折り'));
await student.createClaim('4','',valuable.id);assert((await student.load()).claims.some(c=>c.itemId==='4'));
const stranger=new WorkflowService(new DemoRepository({...DEMO_STUDENT,id:'student-2',email:'s260002@stu.kobe-u.ac.jp'}));
assert.equal((await stranger.load()).notices.length,0);assert.equal((await stranger.load()).claims.length,0);
await assert.rejects(()=>stranger.createClaim('4',''));
await assert.rejects(()=>new WorkflowService(new DemoRepository({...DEMO_STUDENT})).returnItem('1',DEMO_STUDENT.email,'',true));
// Walk-ins also get a private receipt; failed publication can be reconciled later.
await staff.returnItem('1',DEMO_STUDENT.email,'',true);
const walk=(await student.load()).notices.find(n=>n.kind==='RETURN' && n.itemId==='1')!;assert(walk.claimId.startsWith('walkin-'));
await student.saveThanks(walk.claimId,'窓口で受け取れました');await staff.reconcile();
await assert.rejects(()=>staff.correctReturn('1',''));
await staff.correctReturn('1','引き渡し前に対象違いに気付いた');
assert((await student.load()).items.some(i=>i.id==='1'));
assert(!(await student.load()).notices.some(n=>n.id===walk.id));
assert(!(await student.load()).thanks.some(t=>t.message==='窓口で受け取れました'));
assert.equal((await staff.load()).items.find(i=>i.id==='1')!.audit!.length,1);
const original=staff.repo.put.bind(staff.repo);let fail=true;
staff.repo.put=async(table,value,id,etag)=>{if(table==='public'&&fail){fail=false;throw new Error('network');}return original(table,value,id,etag);};
await assert.rejects(()=>staff.saveItem({parent:'P06',category:'P06_PENCIL_CASE',title:'ペンケース',colors:['黒'],campus:'C02',building:'',place:'',foundOn:today(),window:'農学部事務室',feature:'',valuable:false}),/保存は完了/);
const count=(await staff.load()).items.length;await staff.reconcile();assert.equal((await staff.load()).items.length,count);
assert((await student.load()).items.some(i=>i.id===String(count)));
const stale=(await staff.load()).items.find(i=>i.id==='1')!;await staff.repo.put('items',{...stale,feature:'updated'},stale.id,stale.etag);
await assert.rejects(()=>staff.repo.put('items',stale,stale.id,stale.etag));
console.log('PASS: 複数色OR、貴重品非公開、登録イベント照合、通知重複防止、申出引継ぎ、本人確認、二重返却防止、公開取消、解決状態、感謝公開、個別案内、利用者隔離');
}
test().catch(e=>{console.error(e);process.exitCode=1;});
